// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { AlertmanagerConfigArgs } from "./alertmanagerConfig";
export type AlertmanagerConfig = import("./alertmanagerConfig").AlertmanagerConfig;
export const AlertmanagerConfig: typeof import("./alertmanagerConfig").AlertmanagerConfig = null as any;
utilities.lazyLoad(exports, ["AlertmanagerConfig"], () => require("./alertmanagerConfig"));

export { AlertmanagerConfigListArgs } from "./alertmanagerConfigList";
export type AlertmanagerConfigList = import("./alertmanagerConfigList").AlertmanagerConfigList;
export const AlertmanagerConfigList: typeof import("./alertmanagerConfigList").AlertmanagerConfigList = null as any;
utilities.lazyLoad(exports, ["AlertmanagerConfigList"], () => require("./alertmanagerConfigList"));

export { AlertmanagerConfigPatchArgs } from "./alertmanagerConfigPatch";
export type AlertmanagerConfigPatch = import("./alertmanagerConfigPatch").AlertmanagerConfigPatch;
export const AlertmanagerConfigPatch: typeof import("./alertmanagerConfigPatch").AlertmanagerConfigPatch = null as any;
utilities.lazyLoad(exports, ["AlertmanagerConfigPatch"], () => require("./alertmanagerConfigPatch"));

export { PrometheusAgentArgs } from "./prometheusAgent";
export type PrometheusAgent = import("./prometheusAgent").PrometheusAgent;
export const PrometheusAgent: typeof import("./prometheusAgent").PrometheusAgent = null as any;
utilities.lazyLoad(exports, ["PrometheusAgent"], () => require("./prometheusAgent"));

export { PrometheusAgentListArgs } from "./prometheusAgentList";
export type PrometheusAgentList = import("./prometheusAgentList").PrometheusAgentList;
export const PrometheusAgentList: typeof import("./prometheusAgentList").PrometheusAgentList = null as any;
utilities.lazyLoad(exports, ["PrometheusAgentList"], () => require("./prometheusAgentList"));

export { PrometheusAgentPatchArgs } from "./prometheusAgentPatch";
export type PrometheusAgentPatch = import("./prometheusAgentPatch").PrometheusAgentPatch;
export const PrometheusAgentPatch: typeof import("./prometheusAgentPatch").PrometheusAgentPatch = null as any;
utilities.lazyLoad(exports, ["PrometheusAgentPatch"], () => require("./prometheusAgentPatch"));

export { ScrapeConfigArgs } from "./scrapeConfig";
export type ScrapeConfig = import("./scrapeConfig").ScrapeConfig;
export const ScrapeConfig: typeof import("./scrapeConfig").ScrapeConfig = null as any;
utilities.lazyLoad(exports, ["ScrapeConfig"], () => require("./scrapeConfig"));

export { ScrapeConfigListArgs } from "./scrapeConfigList";
export type ScrapeConfigList = import("./scrapeConfigList").ScrapeConfigList;
export const ScrapeConfigList: typeof import("./scrapeConfigList").ScrapeConfigList = null as any;
utilities.lazyLoad(exports, ["ScrapeConfigList"], () => require("./scrapeConfigList"));

export { ScrapeConfigPatchArgs } from "./scrapeConfigPatch";
export type ScrapeConfigPatch = import("./scrapeConfigPatch").ScrapeConfigPatch;
export const ScrapeConfigPatch: typeof import("./scrapeConfigPatch").ScrapeConfigPatch = null as any;
utilities.lazyLoad(exports, ["ScrapeConfigPatch"], () => require("./scrapeConfigPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:monitoring.coreos.com/v1alpha1:AlertmanagerConfig":
                return new AlertmanagerConfig(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:AlertmanagerConfigList":
                return new AlertmanagerConfigList(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:AlertmanagerConfigPatch":
                return new AlertmanagerConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:PrometheusAgent":
                return new PrometheusAgent(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:PrometheusAgentList":
                return new PrometheusAgentList(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:PrometheusAgentPatch":
                return new PrometheusAgentPatch(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:ScrapeConfig":
                return new ScrapeConfig(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:ScrapeConfigList":
                return new ScrapeConfigList(name, <any>undefined, { urn })
            case "kubernetes:monitoring.coreos.com/v1alpha1:ScrapeConfigPatch":
                return new ScrapeConfigPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "monitoring.coreos.com/v1alpha1", _module)
