// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ObjectStoreArgs } from "./objectStore";
export type ObjectStore = import("./objectStore").ObjectStore;
export const ObjectStore: typeof import("./objectStore").ObjectStore = null as any;
utilities.lazyLoad(exports, ["ObjectStore"], () => require("./objectStore"));

export { ObjectStoreListArgs } from "./objectStoreList";
export type ObjectStoreList = import("./objectStoreList").ObjectStoreList;
export const ObjectStoreList: typeof import("./objectStoreList").ObjectStoreList = null as any;
utilities.lazyLoad(exports, ["ObjectStoreList"], () => require("./objectStoreList"));

export { ObjectStorePatchArgs } from "./objectStorePatch";
export type ObjectStorePatch = import("./objectStorePatch").ObjectStorePatch;
export const ObjectStorePatch: typeof import("./objectStorePatch").ObjectStorePatch = null as any;
utilities.lazyLoad(exports, ["ObjectStorePatch"], () => require("./objectStorePatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:barmancloud.cnpg.io/v1:ObjectStore":
                return new ObjectStore(name, <any>undefined, { urn })
            case "kubernetes:barmancloud.cnpg.io/v1:ObjectStoreList":
                return new ObjectStoreList(name, <any>undefined, { urn })
            case "kubernetes:barmancloud.cnpg.io/v1:ObjectStorePatch":
                return new ObjectStorePatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "barmancloud.cnpg.io/v1", _module)
