// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { AcceleratorFunctionArgs } from "./acceleratorFunction";
export type AcceleratorFunction = import("./acceleratorFunction").AcceleratorFunction;
export const AcceleratorFunction: typeof import("./acceleratorFunction").AcceleratorFunction = null as any;
utilities.lazyLoad(exports, ["AcceleratorFunction"], () => require("./acceleratorFunction"));

export { FpgaRegionArgs } from "./fpgaRegion";
export type FpgaRegion = import("./fpgaRegion").FpgaRegion;
export const FpgaRegion: typeof import("./fpgaRegion").FpgaRegion = null as any;
utilities.lazyLoad(exports, ["FpgaRegion"], () => require("./fpgaRegion"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:fpga.intel.com/v2:AcceleratorFunction":
                return new AcceleratorFunction(name, <any>undefined, { urn })
            case "kubernetes:fpga.intel.com/v2:FpgaRegion":
                return new FpgaRegion(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "fpga.intel.com/v2", _module)
