// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * DlbDevicePlugin is the Schema for the dlbdeviceplugins API. It represents the DLB device plugin responsible for advertising Intel DLB hardware resources to the kubelet.
 */
export class DlbDevicePlugin extends pulumi.CustomResource {
    /**
     * Get an existing DlbDevicePlugin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DlbDevicePlugin {
        return new DlbDevicePlugin(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:deviceplugin.intel.com/v1:DlbDevicePlugin';

    /**
     * Returns true if the given object is an instance of DlbDevicePlugin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DlbDevicePlugin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DlbDevicePlugin.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"deviceplugin.intel.com/v1">;
    public readonly kind!: pulumi.Output<"DlbDevicePlugin">;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * DlbDevicePluginSpec defines the desired state of DlbDevicePlugin.
     */
    public readonly spec!: pulumi.Output<outputs.deviceplugin.v1.DlbDevicePluginSpec | undefined>;
    /**
     * DlbDevicePluginStatus defines the observed state of DlbDevicePlugin.
     */
    public readonly status!: pulumi.Output<outputs.deviceplugin.v1.DlbDevicePluginStatus | undefined>;

    /**
     * Create a DlbDevicePlugin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DlbDevicePluginArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "deviceplugin.intel.com/v1";
            resourceInputs["kind"] = "DlbDevicePlugin";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DlbDevicePlugin.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DlbDevicePlugin resource.
 */
export interface DlbDevicePluginArgs {
    apiVersion?: pulumi.Input<"deviceplugin.intel.com/v1">;
    kind?: pulumi.Input<"DlbDevicePlugin">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * DlbDevicePluginSpec defines the desired state of DlbDevicePlugin.
     */
    spec?: pulumi.Input<inputs.deviceplugin.v1.DlbDevicePluginSpecArgs>;
    /**
     * DlbDevicePluginStatus defines the observed state of DlbDevicePlugin.
     */
    status?: pulumi.Input<inputs.deviceplugin.v1.DlbDevicePluginStatusArgs>;
}
