// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * IaaDevicePlugin is the Schema for the iaadeviceplugins API. It represents the IAA device plugin responsible for advertising Intel IAA hardware resources to the kubelet.
 */
export class IaaDevicePlugin extends pulumi.CustomResource {
    /**
     * Get an existing IaaDevicePlugin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): IaaDevicePlugin {
        return new IaaDevicePlugin(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:deviceplugin.intel.com/v1:IaaDevicePlugin';

    /**
     * Returns true if the given object is an instance of IaaDevicePlugin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IaaDevicePlugin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IaaDevicePlugin.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"deviceplugin.intel.com/v1">;
    public readonly kind!: pulumi.Output<"IaaDevicePlugin">;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * IaaDevicePluginSpec defines the desired state of IaaDevicePlugin.
     */
    public readonly spec!: pulumi.Output<outputs.deviceplugin.v1.IaaDevicePluginSpec | undefined>;
    /**
     * IaaDevicePluginStatus defines the observed state of IaaDevicePlugin.
     */
    public readonly status!: pulumi.Output<outputs.deviceplugin.v1.IaaDevicePluginStatus | undefined>;

    /**
     * Create a IaaDevicePlugin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IaaDevicePluginArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "deviceplugin.intel.com/v1";
            resourceInputs["kind"] = "IaaDevicePlugin";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IaaDevicePlugin.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a IaaDevicePlugin resource.
 */
export interface IaaDevicePluginArgs {
    apiVersion?: pulumi.Input<"deviceplugin.intel.com/v1">;
    kind?: pulumi.Input<"IaaDevicePlugin">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * IaaDevicePluginSpec defines the desired state of IaaDevicePlugin.
     */
    spec?: pulumi.Input<inputs.deviceplugin.v1.IaaDevicePluginSpecArgs>;
    /**
     * IaaDevicePluginStatus defines the observed state of IaaDevicePlugin.
     */
    status?: pulumi.Input<inputs.deviceplugin.v1.IaaDevicePluginStatusArgs>;
}
