// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * QatDevicePlugin is the Schema for the qatdeviceplugins API. It represents the QAT device plugin responsible for advertising Intel QuickAssist Technology hardware resources to the kubelet.
 */
export class QatDevicePlugin extends pulumi.CustomResource {
    /**
     * Get an existing QatDevicePlugin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): QatDevicePlugin {
        return new QatDevicePlugin(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:deviceplugin.intel.com/v1:QatDevicePlugin';

    /**
     * Returns true if the given object is an instance of QatDevicePlugin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is QatDevicePlugin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === QatDevicePlugin.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"deviceplugin.intel.com/v1">;
    public readonly kind!: pulumi.Output<"QatDevicePlugin">;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * QatDevicePluginSpec defines the desired state of QatDevicePlugin.
     */
    public readonly spec!: pulumi.Output<outputs.deviceplugin.v1.QatDevicePluginSpec | undefined>;
    /**
     * QatDevicePluginStatus defines the observed state of QatDevicePlugin. TODO(rojkov): consider code deduplication with GpuDevicePluginStatus.
     */
    public readonly status!: pulumi.Output<outputs.deviceplugin.v1.QatDevicePluginStatus | undefined>;

    /**
     * Create a QatDevicePlugin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: QatDevicePluginArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "deviceplugin.intel.com/v1";
            resourceInputs["kind"] = "QatDevicePlugin";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(QatDevicePlugin.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a QatDevicePlugin resource.
 */
export interface QatDevicePluginArgs {
    apiVersion?: pulumi.Input<"deviceplugin.intel.com/v1">;
    kind?: pulumi.Input<"QatDevicePlugin">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * QatDevicePluginSpec defines the desired state of QatDevicePlugin.
     */
    spec?: pulumi.Input<inputs.deviceplugin.v1.QatDevicePluginSpecArgs>;
    /**
     * QatDevicePluginStatus defines the observed state of QatDevicePlugin. TODO(rojkov): consider code deduplication with GpuDevicePluginStatus.
     */
    status?: pulumi.Input<inputs.deviceplugin.v1.QatDevicePluginStatusArgs>;
}
