// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { AccessControlPolicyArgs } from "./accessControlPolicy";
export type AccessControlPolicy = import("./accessControlPolicy").AccessControlPolicy;
export const AccessControlPolicy: typeof import("./accessControlPolicy").AccessControlPolicy = null as any;
utilities.lazyLoad(exports, ["AccessControlPolicy"], () => require("./accessControlPolicy"));

export { AccessControlPolicyListArgs } from "./accessControlPolicyList";
export type AccessControlPolicyList = import("./accessControlPolicyList").AccessControlPolicyList;
export const AccessControlPolicyList: typeof import("./accessControlPolicyList").AccessControlPolicyList = null as any;
utilities.lazyLoad(exports, ["AccessControlPolicyList"], () => require("./accessControlPolicyList"));

export { AccessControlPolicyPatchArgs } from "./accessControlPolicyPatch";
export type AccessControlPolicyPatch = import("./accessControlPolicyPatch").AccessControlPolicyPatch;
export const AccessControlPolicyPatch: typeof import("./accessControlPolicyPatch").AccessControlPolicyPatch = null as any;
utilities.lazyLoad(exports, ["AccessControlPolicyPatch"], () => require("./accessControlPolicyPatch"));

export { AIServiceArgs } from "./aiservice";
export type AIService = import("./aiservice").AIService;
export const AIService: typeof import("./aiservice").AIService = null as any;
utilities.lazyLoad(exports, ["AIService"], () => require("./aiservice"));

export { AIServiceListArgs } from "./aiserviceList";
export type AIServiceList = import("./aiserviceList").AIServiceList;
export const AIServiceList: typeof import("./aiserviceList").AIServiceList = null as any;
utilities.lazyLoad(exports, ["AIServiceList"], () => require("./aiserviceList"));

export { AIServicePatchArgs } from "./aiservicePatch";
export type AIServicePatch = import("./aiservicePatch").AIServicePatch;
export const AIServicePatch: typeof import("./aiservicePatch").AIServicePatch = null as any;
utilities.lazyLoad(exports, ["AIServicePatch"], () => require("./aiservicePatch"));

export { APIArgs } from "./api";
export type API = import("./api").API;
export const API: typeof import("./api").API = null as any;
utilities.lazyLoad(exports, ["API"], () => require("./api"));

export { APIAuthArgs } from "./apiauth";
export type APIAuth = import("./apiauth").APIAuth;
export const APIAuth: typeof import("./apiauth").APIAuth = null as any;
utilities.lazyLoad(exports, ["APIAuth"], () => require("./apiauth"));

export { APIAuthListArgs } from "./apiauthList";
export type APIAuthList = import("./apiauthList").APIAuthList;
export const APIAuthList: typeof import("./apiauthList").APIAuthList = null as any;
utilities.lazyLoad(exports, ["APIAuthList"], () => require("./apiauthList"));

export { APIAuthPatchArgs } from "./apiauthPatch";
export type APIAuthPatch = import("./apiauthPatch").APIAuthPatch;
export const APIAuthPatch: typeof import("./apiauthPatch").APIAuthPatch = null as any;
utilities.lazyLoad(exports, ["APIAuthPatch"], () => require("./apiauthPatch"));

export { APIBundleArgs } from "./apibundle";
export type APIBundle = import("./apibundle").APIBundle;
export const APIBundle: typeof import("./apibundle").APIBundle = null as any;
utilities.lazyLoad(exports, ["APIBundle"], () => require("./apibundle"));

export { APIBundleListArgs } from "./apibundleList";
export type APIBundleList = import("./apibundleList").APIBundleList;
export const APIBundleList: typeof import("./apibundleList").APIBundleList = null as any;
utilities.lazyLoad(exports, ["APIBundleList"], () => require("./apibundleList"));

export { APIBundlePatchArgs } from "./apibundlePatch";
export type APIBundlePatch = import("./apibundlePatch").APIBundlePatch;
export const APIBundlePatch: typeof import("./apibundlePatch").APIBundlePatch = null as any;
utilities.lazyLoad(exports, ["APIBundlePatch"], () => require("./apibundlePatch"));

export { APICatalogItemArgs } from "./apicatalogItem";
export type APICatalogItem = import("./apicatalogItem").APICatalogItem;
export const APICatalogItem: typeof import("./apicatalogItem").APICatalogItem = null as any;
utilities.lazyLoad(exports, ["APICatalogItem"], () => require("./apicatalogItem"));

export { APICatalogItemListArgs } from "./apicatalogItemList";
export type APICatalogItemList = import("./apicatalogItemList").APICatalogItemList;
export const APICatalogItemList: typeof import("./apicatalogItemList").APICatalogItemList = null as any;
utilities.lazyLoad(exports, ["APICatalogItemList"], () => require("./apicatalogItemList"));

export { APICatalogItemPatchArgs } from "./apicatalogItemPatch";
export type APICatalogItemPatch = import("./apicatalogItemPatch").APICatalogItemPatch;
export const APICatalogItemPatch: typeof import("./apicatalogItemPatch").APICatalogItemPatch = null as any;
utilities.lazyLoad(exports, ["APICatalogItemPatch"], () => require("./apicatalogItemPatch"));

export { APIListArgs } from "./apilist";
export type APIList = import("./apilist").APIList;
export const APIList: typeof import("./apilist").APIList = null as any;
utilities.lazyLoad(exports, ["APIList"], () => require("./apilist"));

export { APIPatchArgs } from "./apipatch";
export type APIPatch = import("./apipatch").APIPatch;
export const APIPatch: typeof import("./apipatch").APIPatch = null as any;
utilities.lazyLoad(exports, ["APIPatch"], () => require("./apipatch"));

export { APIPlanArgs } from "./apiplan";
export type APIPlan = import("./apiplan").APIPlan;
export const APIPlan: typeof import("./apiplan").APIPlan = null as any;
utilities.lazyLoad(exports, ["APIPlan"], () => require("./apiplan"));

export { APIPlanListArgs } from "./apiplanList";
export type APIPlanList = import("./apiplanList").APIPlanList;
export const APIPlanList: typeof import("./apiplanList").APIPlanList = null as any;
utilities.lazyLoad(exports, ["APIPlanList"], () => require("./apiplanList"));

export { APIPlanPatchArgs } from "./apiplanPatch";
export type APIPlanPatch = import("./apiplanPatch").APIPlanPatch;
export const APIPlanPatch: typeof import("./apiplanPatch").APIPlanPatch = null as any;
utilities.lazyLoad(exports, ["APIPlanPatch"], () => require("./apiplanPatch"));

export { APIPortalArgs } from "./apiportal";
export type APIPortal = import("./apiportal").APIPortal;
export const APIPortal: typeof import("./apiportal").APIPortal = null as any;
utilities.lazyLoad(exports, ["APIPortal"], () => require("./apiportal"));

export { APIPortalAuthArgs } from "./apiportalAuth";
export type APIPortalAuth = import("./apiportalAuth").APIPortalAuth;
export const APIPortalAuth: typeof import("./apiportalAuth").APIPortalAuth = null as any;
utilities.lazyLoad(exports, ["APIPortalAuth"], () => require("./apiportalAuth"));

export { APIPortalAuthListArgs } from "./apiportalAuthList";
export type APIPortalAuthList = import("./apiportalAuthList").APIPortalAuthList;
export const APIPortalAuthList: typeof import("./apiportalAuthList").APIPortalAuthList = null as any;
utilities.lazyLoad(exports, ["APIPortalAuthList"], () => require("./apiportalAuthList"));

export { APIPortalAuthPatchArgs } from "./apiportalAuthPatch";
export type APIPortalAuthPatch = import("./apiportalAuthPatch").APIPortalAuthPatch;
export const APIPortalAuthPatch: typeof import("./apiportalAuthPatch").APIPortalAuthPatch = null as any;
utilities.lazyLoad(exports, ["APIPortalAuthPatch"], () => require("./apiportalAuthPatch"));

export { APIPortalListArgs } from "./apiportalList";
export type APIPortalList = import("./apiportalList").APIPortalList;
export const APIPortalList: typeof import("./apiportalList").APIPortalList = null as any;
utilities.lazyLoad(exports, ["APIPortalList"], () => require("./apiportalList"));

export { APIPortalPatchArgs } from "./apiportalPatch";
export type APIPortalPatch = import("./apiportalPatch").APIPortalPatch;
export const APIPortalPatch: typeof import("./apiportalPatch").APIPortalPatch = null as any;
utilities.lazyLoad(exports, ["APIPortalPatch"], () => require("./apiportalPatch"));

export { APIRateLimitArgs } from "./apirateLimit";
export type APIRateLimit = import("./apirateLimit").APIRateLimit;
export const APIRateLimit: typeof import("./apirateLimit").APIRateLimit = null as any;
utilities.lazyLoad(exports, ["APIRateLimit"], () => require("./apirateLimit"));

export { APIRateLimitListArgs } from "./apirateLimitList";
export type APIRateLimitList = import("./apirateLimitList").APIRateLimitList;
export const APIRateLimitList: typeof import("./apirateLimitList").APIRateLimitList = null as any;
utilities.lazyLoad(exports, ["APIRateLimitList"], () => require("./apirateLimitList"));

export { APIRateLimitPatchArgs } from "./apirateLimitPatch";
export type APIRateLimitPatch = import("./apirateLimitPatch").APIRateLimitPatch;
export const APIRateLimitPatch: typeof import("./apirateLimitPatch").APIRateLimitPatch = null as any;
utilities.lazyLoad(exports, ["APIRateLimitPatch"], () => require("./apirateLimitPatch"));

export { APIVersionArgs } from "./apiversion";
export type APIVersion = import("./apiversion").APIVersion;
export const APIVersion: typeof import("./apiversion").APIVersion = null as any;
utilities.lazyLoad(exports, ["APIVersion"], () => require("./apiversion"));

export { APIVersionListArgs } from "./apiversionList";
export type APIVersionList = import("./apiversionList").APIVersionList;
export const APIVersionList: typeof import("./apiversionList").APIVersionList = null as any;
utilities.lazyLoad(exports, ["APIVersionList"], () => require("./apiversionList"));

export { APIVersionPatchArgs } from "./apiversionPatch";
export type APIVersionPatch = import("./apiversionPatch").APIVersionPatch;
export const APIVersionPatch: typeof import("./apiversionPatch").APIVersionPatch = null as any;
utilities.lazyLoad(exports, ["APIVersionPatch"], () => require("./apiversionPatch"));

export { ContentItemArgs } from "./contentItem";
export type ContentItem = import("./contentItem").ContentItem;
export const ContentItem: typeof import("./contentItem").ContentItem = null as any;
utilities.lazyLoad(exports, ["ContentItem"], () => require("./contentItem"));

export { ContentItemListArgs } from "./contentItemList";
export type ContentItemList = import("./contentItemList").ContentItemList;
export const ContentItemList: typeof import("./contentItemList").ContentItemList = null as any;
utilities.lazyLoad(exports, ["ContentItemList"], () => require("./contentItemList"));

export { ContentItemPatchArgs } from "./contentItemPatch";
export type ContentItemPatch = import("./contentItemPatch").ContentItemPatch;
export const ContentItemPatch: typeof import("./contentItemPatch").ContentItemPatch = null as any;
utilities.lazyLoad(exports, ["ContentItemPatch"], () => require("./contentItemPatch"));

export { ManagedApplicationArgs } from "./managedApplication";
export type ManagedApplication = import("./managedApplication").ManagedApplication;
export const ManagedApplication: typeof import("./managedApplication").ManagedApplication = null as any;
utilities.lazyLoad(exports, ["ManagedApplication"], () => require("./managedApplication"));

export { ManagedApplicationListArgs } from "./managedApplicationList";
export type ManagedApplicationList = import("./managedApplicationList").ManagedApplicationList;
export const ManagedApplicationList: typeof import("./managedApplicationList").ManagedApplicationList = null as any;
utilities.lazyLoad(exports, ["ManagedApplicationList"], () => require("./managedApplicationList"));

export { ManagedApplicationPatchArgs } from "./managedApplicationPatch";
export type ManagedApplicationPatch = import("./managedApplicationPatch").ManagedApplicationPatch;
export const ManagedApplicationPatch: typeof import("./managedApplicationPatch").ManagedApplicationPatch = null as any;
utilities.lazyLoad(exports, ["ManagedApplicationPatch"], () => require("./managedApplicationPatch"));

export { ManagedSubscriptionArgs } from "./managedSubscription";
export type ManagedSubscription = import("./managedSubscription").ManagedSubscription;
export const ManagedSubscription: typeof import("./managedSubscription").ManagedSubscription = null as any;
utilities.lazyLoad(exports, ["ManagedSubscription"], () => require("./managedSubscription"));

export { ManagedSubscriptionListArgs } from "./managedSubscriptionList";
export type ManagedSubscriptionList = import("./managedSubscriptionList").ManagedSubscriptionList;
export const ManagedSubscriptionList: typeof import("./managedSubscriptionList").ManagedSubscriptionList = null as any;
utilities.lazyLoad(exports, ["ManagedSubscriptionList"], () => require("./managedSubscriptionList"));

export { ManagedSubscriptionPatchArgs } from "./managedSubscriptionPatch";
export type ManagedSubscriptionPatch = import("./managedSubscriptionPatch").ManagedSubscriptionPatch;
export const ManagedSubscriptionPatch: typeof import("./managedSubscriptionPatch").ManagedSubscriptionPatch = null as any;
utilities.lazyLoad(exports, ["ManagedSubscriptionPatch"], () => require("./managedSubscriptionPatch"));

export { UplinkArgs } from "./uplink";
export type Uplink = import("./uplink").Uplink;
export const Uplink: typeof import("./uplink").Uplink = null as any;
utilities.lazyLoad(exports, ["Uplink"], () => require("./uplink"));

export { UplinkListArgs } from "./uplinkList";
export type UplinkList = import("./uplinkList").UplinkList;
export const UplinkList: typeof import("./uplinkList").UplinkList = null as any;
utilities.lazyLoad(exports, ["UplinkList"], () => require("./uplinkList"));

export { UplinkPatchArgs } from "./uplinkPatch";
export type UplinkPatch = import("./uplinkPatch").UplinkPatch;
export const UplinkPatch: typeof import("./uplinkPatch").UplinkPatch = null as any;
utilities.lazyLoad(exports, ["UplinkPatch"], () => require("./uplinkPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:hub.traefik.io/v1alpha1:AIService":
                return new AIService(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:AIServiceList":
                return new AIServiceList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:AIServicePatch":
                return new AIServicePatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:API":
                return new API(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIAuth":
                return new APIAuth(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIAuthList":
                return new APIAuthList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIAuthPatch":
                return new APIAuthPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIBundle":
                return new APIBundle(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIBundleList":
                return new APIBundleList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIBundlePatch":
                return new APIBundlePatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APICatalogItem":
                return new APICatalogItem(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APICatalogItemList":
                return new APICatalogItemList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APICatalogItemPatch":
                return new APICatalogItemPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIList":
                return new APIList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPatch":
                return new APIPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPlan":
                return new APIPlan(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPlanList":
                return new APIPlanList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPlanPatch":
                return new APIPlanPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPortal":
                return new APIPortal(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPortalAuth":
                return new APIPortalAuth(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPortalAuthList":
                return new APIPortalAuthList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPortalAuthPatch":
                return new APIPortalAuthPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPortalList":
                return new APIPortalList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIPortalPatch":
                return new APIPortalPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIRateLimit":
                return new APIRateLimit(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIRateLimitList":
                return new APIRateLimitList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIRateLimitPatch":
                return new APIRateLimitPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIVersion":
                return new APIVersion(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIVersionList":
                return new APIVersionList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:APIVersionPatch":
                return new APIVersionPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:AccessControlPolicy":
                return new AccessControlPolicy(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:AccessControlPolicyList":
                return new AccessControlPolicyList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:AccessControlPolicyPatch":
                return new AccessControlPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ContentItem":
                return new ContentItem(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ContentItemList":
                return new ContentItemList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ContentItemPatch":
                return new ContentItemPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ManagedApplication":
                return new ManagedApplication(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ManagedApplicationList":
                return new ManagedApplicationList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ManagedApplicationPatch":
                return new ManagedApplicationPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ManagedSubscription":
                return new ManagedSubscription(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ManagedSubscriptionList":
                return new ManagedSubscriptionList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:ManagedSubscriptionPatch":
                return new ManagedSubscriptionPatch(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:Uplink":
                return new Uplink(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:UplinkList":
                return new UplinkList(name, <any>undefined, { urn })
            case "kubernetes:hub.traefik.io/v1alpha1:UplinkPatch":
                return new UplinkPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "hub.traefik.io/v1alpha1", _module)
